version: '3'
 
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-storage:/data
    environment:
      MINIO_ROOT_USER: 
      MINIO_ROOT_PASSWORD: 
      MINIO_IDENTITY_OPENID_CONFIG_URL: https://platform.beopendep.it/auth/realms/master/.well-known/openid-configuration
      MINIO_BROWSER_REDIRECT_URL: 'http://localhost:9001'
      MINIO_IDENTITY_OPENID_CLIENT_ID: 
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: 
      MINIO_IDENTITY_OPENID_SCOPES: 'openid profile email'
      MINIO_IDENTITY_OPENID_CLAIM_NAME: policy
      MINIO_IDENTITY_OPENID_REDIRECT_URI: http://localhost:9001/oauth_callback
    command: server --console-address ":9001" /data

volumes:
  minio-storage: {}